config/routes.rb
Rails.application.routes.draw do
 
  root 'videos#index'

  get 'signup' => 'users#new'

  get 'sessions/new'

  get    'login'   => 'sessions#new'

  post   'login'   => 'sessions#create'
  
  get 'logout'  => 'sessions#destroy'

  get 'upload' => 'videos#upload'

  resources :users, :except => [:index]

  resources :videos do
    member do
      put "like", to: "videos#upvote"
      put "dislike", to: "videos#downvote"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :videos
	acts_as_voter
	has_secure_password
	validates :email, presence: true, uniqueness: true
end

app/models/video.rb
class Video < ActiveRecord::Base
	belongs_to :user
	acts_as_votable
	# mount_uploader :video, VideoUploader

	#total score for each video - This will be displayed by video and used for positioning based on score
	def score
		self.get_upvotes.size - self.get_downvotes.size
	end


	def self.sorted_by_votes
		#&: is shortcut for {|video| video.score}
	  Video.all.sort_by(&:score).reverse
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:session][:email])
  	if user && user.authenticate(params[:session][:password])
  		log_in user
       flash[:success] = "You have successfully logged in"
  		redirect_to root_path
  	else
  		flash[:danger] = 'Invalid email or password'
  		render 'new'
  end
end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
# before_filter :authorize, only: [:edit, :update]
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
      flash[:success] = "You have successfully Signed Up"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:success] = "Profile updated"
         redirect_to @user
      else
        render 'edit'
      end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to root_path
  end

  
 private
  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # before_filter :authorize, only: [:edit, :update]
 

  def index
  	@videos = Video.sorted_by_votes
  end

  def show
	  @video = Video.find(params[:id])  
  end

  def new
  	@video = Video.new
  end

  def create
      require 'json'
      # print(params['video']['filedate'])
      videoFile = video_params["filedata"]
      filename = videoFile.original_filename
      videoPath = videoFile.tempfile
      print("filename=========",videoPath)
      # print("videoFile=====", videoFile)      
      @response = HTTMultiParty.post('https://api.vid.me/video/upload', :query => {:filedata => File.new(videoPath)}, :headers => { 'Content-Type' => 'video/x-msvideo'}, :detect_mime_type => true)
      @response.to_hash.to_json
      videoData = JSON.parse(@response)
      # print("video data:=========", videoData)      
      # puts videoData['video']['embed_url']
      @embedURL = videoData['video']['embed_url']
    @video = Video.new(video_params)
    @video.url = @embedURL
    @video.user_id = current_user.id
  	if @video.save
      flash[:success] = "Video has been uploaded"
  		redirect_to current_user
  	else
  		render 'new'
  	end
  end


  def edit
    @video = Video.find(params[:id])
  end


  def update
      @video = Video.find(params[:id])
      if @video.update_attributes(video_params)
        flash[:success] = "Video updated"
        redirect_to current_user
      else
        render 'edit'
      end
  end



  def destroy
      Video.find(params[:id]).destroy
      redirect_to current_user
  end
    # def date_published
    #   created_at.localtime.strftime("%A, %B, %-d, %Y at %l:%M %p")
    # end

#allow user to upvote on videos  in gallery
  def upvote
    @video = Video.find(params[:id])
    @video.upvote_by current_user
    redirect_to videos_path
  end

  #allow user to downvote on videos  in gallery
  def downvote
    @video = Video.find(params[:id])
    @video.downvote_by current_user
    redirect_to videos_path
  end

private
def video_params
      params.require(:video).permit(:title, :description, :url, :remote_video_url, :filedata)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
# this method will embed the code from the partial
  def upload_video(url)
    render :partial => 'shared/video', :locals => { :url => url }
  end 
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	 def current_user
   		 @current_user ||= User.find(session[:user_id]) if session[:user_id]
   		 # redirect_to(root_url) unless current_user?(@user)
   end


  	 def logged_in?
      !current_user.nil?
    end

    def authorize
      redirect_to '/login' unless @current_user
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">StreetScout</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><%#= link_to "Home", root_path %><span class="sr-only">(current)</span></li> -->
        <% if logged_in? %>
            <li><%= link_to "Profile", @current_user %></li>
             <!-- <li><%#= link_to "All Videos", videos_path%></li> -->
            <li><%= link_to "Upload New Video", new_video_path %></li> 
            <li class="dropdown nav pull-right">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
            <li><%= link_to "Log out", logout_path%></li>
            <li><%= link_to 'Delete Account', @user, method: :delete, data: { confirm: 'Are you sure?' }%></li>
          </ul>
        </li>
        <% else %>
            <!-- <li><%#= link_to "All Videos", videos_path%></li> -->
            <li><%= link_to "Log in", login_path %></li>
            <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_videolist.html.erb
<div class="video-container">
<%= @videos.each do |v| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%="Title:" + " " + v.title %></h3>
  </div>
  <div class="panel-body" style="max-width: 600; max-height:400;">
  	<% if logged_in? %>
  	<%="Uploaded by:" + " " + v.user.name%><br>
    <%="Description:" + " " + v.description%><br>
    <%=link_to "Upvote", like_video_path(v), method: :put%>
	<%=link_to "Downvote", dislike_video_path(v), method: :put%>
	Score: <%=v.score%><br>
	<%= upload_video v.url %>
	<%else%>
	<%="Uploaded by:" + " " + v.user.name%><br>
    <%="Description:" + " " + v.description%><br>
    <%= link_to "Must Be Logged In to Vote!", login_path%>
	Score: <%=v.score%><br>
	<%= upload_video v.url %>
	<%end%>
  </div> 
</div>
<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StreetScout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class='container'>
	<% flash.each do |message_type, message| %>
	    <div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>
<%= yield %>


</div>
</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
	<div class="container">
  		<h1>Welcome to Street Scout</h1>
  		<h3>Share local street artist talent with the world!</h3>
  		<!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p> -->
	</div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <p>Sign Up! Create an account to start posting videos</p>
    </div>
    <div class="col-sm-4">
      <p>Upload videos of your favorite street artists to share their talents with the world.</p>
    </div>
    <div class="col-sm-4">
      <p>View and vote on all video uploads.  At the end of the week, the video with the highest score will be featured with the potential for this website's creator to see!</p>
    </div>
  </div>
</div>

app/views/shared/_errors_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_video.html.erb
<!-- <iframe width="500" height="350" src="<%= url %>" frameborder="0" allowfullscreen></iframe>  -->

<!-- 16:9 aspect ratio -->
<div class="embed-responsive embed-responsive-16by9 video-container" allowfullscreen>
  <iframe class="embed-responsive-item" src="<%= url %>"></iframe>
</div>

<!-- 4:3 aspect ratio -->
<!-- <div class="embed-responsive embed-responsive-4by3" allowfullscreen>
<<<<<<< HEAD
  <iframe class="embed-responsive-item" src="<%= url %>></iframe>
=======
  <iframe class="embed-responsive-item" src="<%= url %>"></iframe>
>>>>>>> vidme_api
</div> -->

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/errors_messages' %>
      <%= f.text_field :name, placeholder:'Name', class: 'form-control'%><br>
      <%= f.email_field :email, placeholder: 'Email', class: 'form-control'%><br>
      <%= f.password_field :password, placeholder: 'Password', class: 'form-control'%><br>
      <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation', class: 'form-control'%><br>
       <%= f.submit "Create account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/errors_messages' %>
      <%= f.text_field :name, placeholder:'Name', class: 'form-control'%><br>
      <%= f.email_field :email, placeholder: 'Email', class: 'form-control'%><br>
      <%= f.password_field :password, placeholder: 'Password', class: 'form-control'%><br>
      <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation', class: 'form-control'%><br>
       <%= f.submit "Save Changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div>
<%=@users.each do |u| %>
<%="Name:" + " " + u.name%><br>
<%="Email:" + " " + u.email%><br>
<%="Videos:"  %><br>
<%= link_to 'Show', u %><br><br>
<%end%>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%=@user.name%>'s Profile </h1>
<h2>My Videos </h2>

<!-- <a href="http://localhost:3000/videos/new" class="btn btn-default"><span class="glyphicon glyphicon-cloud-upload"></span> Upload New Video</a> -->
<%#= link_to "Upload Video", new_video_path %> 

<div class="video-container">
<%=current_user.videos.each do |v| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%="Title:" + " " + v.title %></h3>
  </div>
  <div class="panel-body" style="max-width: 600; max-height:400;">
    <%="Description:" + " " + v.description%><br>
    <%= link_to 'Edit', edit_video_path(v) %>
	<%= link_to 'Delete', v, method: :delete, data: { confirm: 'Are you sure?' } %>
	Score: <%=v.score%><br>
	<%= upload_video v.url %>
  </div>
</div>
<%end%>
</div>

app/views/videos/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @video do |f| %>
      <%= f.text_field :title, placeholder:'Title', class: 'form-control'%><br>
      <%= f.text_field :description, placeholder: 'Description', class: 'form-control'%><br>
      <!-- #f.text_field :url, placeholder: "Paste Video URL here!",class: 'form-control'  -->
      <%= f.file_field :filedata, class: 'form-control' %><br>
      <%= f.submit "Upload Video", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/videos/edit.html.erb
<h1>Edit Video</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@video) do |f| %>
      <%= f.text_field :title, placeholder:'Title', class: 'form-control'%><br>
      <%= f.text_field :description, placeholder: 'Description', class: 'form-control'%><br>
      <%= f.label :url, "Paste Video URL here!"%>
      <%= f.text_field :url %><br>
      <%= f.submit "Save Video Changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= link_to 'Back', users_path %>

app/views/videos/index.html.erb
<h1>Videos</h1>

<div class="video-container">
<%= @videos.each do |v| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%="Title:" + " " + v.title %></h3>
  </div>
  <div class="panel-body" style="max-width: 600; max-height:400;">
  	<% if logged_in? %>
  	<%="Uploaded by:" + " " + v.user.name%><br>
    <%="Description:" + " " + v.description%><br>
    <%=link_to "Upvote", like_video_path(v), method: :put%>
	<%=link_to "Downvote", dislike_video_path(v), method: :put%>
	Score: <%=v.score%><br>
	<%= v.filedata %> 
	<%else%>
	<%="Uploaded by:" + " " + v.user.name%><br>
    <%="Description:" + " " + v.description%><br>
    <%= link_to "Must Be Logged In to Vote!", login_path%>
	Score: <%=v.score%><br>
	<%= upload_video v.url %>
	<%end%>
  </div> 
</div>
<%end%>
</div>

app/views/videos/new.html.erb
<h1>Upload Video</h1>
<%= render 'form' %>

app/views/videos/show.html.erb
<h1>Videos#show</h1>
<p>Find me in app/views/videos/show.html.erb</p>